### ISSUE TITLE
display flash errors below relevant input boxes / refactor all forms

### ISSUE THREAD

**Issue by leahgoldberg** [nyc-fireflies-2015/mojoe#89]

**Comment by kripple** [comment]
https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/components/errors.rb

**Comment by kripple** [comment]
https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/components/errors.rb

**Comment by kripple** [comment]
simple_form gem has implemented this
